name: Release Erlang libraries
on:
  push:
    branches: [v0]
  pull_request:
    branches: ['**']

env:
  NODEJS_VERSION: '16'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup swagger-codegen
        uses: valitydev/action-setup-swagger-codegen@v0.0.4
        with:
          codegen-version: "2.4.25"
          generator-version: "1.0.3"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODEJS_VERSION }}
          cache: npm

      - name: Install deps
        run: npm install

      - name: Bundle spec and build docsite
        run: npm run build -- web_deploy

      - name: Generate stubs
        run: |
          mkdir -p out
          echo "Generate stubs"
          swagger-codegen generate -l vality-erlang-client -i web_deploy/swagger.json -o out/erlang-client --additional-properties packageName=swag_client
          swagger-codegen generate -l vality-erlang-server -i web_deploy/swagger.json -o out/erlang-server --additional-properties packageName=swag_server
#
      - name: Deploy erlang-client artifact to release branch
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: release/erlang/client/${{ steps.branch.outputs.name }}
          folder: out/erlang-client
          commit-message: Release ${{ github.repository }}@${{ github.sha }}

      - name: Deploy erlang-server artifact to release branch
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: release/erlang/server/${{ steps.branch.outputs.name }}
          folder: out/erlang-server
          commit-message: Release ${{ github.repository }}@${{ github.sha }}